### ISSUE TITLE
Particles: stretch by velocity 

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/roadmap#11]
Previous generations of Godot (1.0 - 2.1) had a feature that allowed to change particle scale in relation to their velocity. It was very useful for sparks, or rain-like particles.

**Comment by kubecz3k** [comment]
Also some idea to consider:
```
reduz: stretch by velocity definitely needs to be added back
reduz: also i think that has to be added in the rendering material,  not the particle material
```

**Comment by akien-mga** [comment]
Please file a proposal on https://github.com/godotengine/godot-proposals, which is the new tracker for feature requests.
