### ISSUE TITLE
License needed!

### ISSUE THREAD

**Issue by est31** [godotengine/roadmap#15]
This seems to have no license. Right now it almost has no content and this means that now is the best moment to settle this. Of course all relevant parties that hold copyright need to sign off on a license change, the safest option is to take the list of contributors.

**Comment by est31** [comment]
And asking the people with open PRs is probably no bad idea either as they might not be aware that their content is now under a license.

**Comment by est31** [comment]
I've also seen that https://github.com/godotengine/website seems to lack a license as well, so maybe some procedure to get the repo licensed should be started, too.

https://github.com/godotengine/godot-docs lacks a dedicated license file but it has a mention about its license in the readme which should be enough. https://github.com/godotengine/godot-modules seems very outdated but many of the relevant files inside have license headers. The other repos under this organisation account seem fine.

**Comment by fire** [comment]
@Calinou We should still probably add a license like https://github.com/godotengine/godot-docs/blob/master/LICENSE.txt

**Comment by yash37158** [comment]
Can I work on this issue?

**Comment by Calinou** [comment]
> Can I work on this issue?

Since this repository is now only used for GSoC project lists, it doesn't need to have a license attached anymore (especially since it's not accepting contributions).

**Comment by anissen** [comment]
@Calinou Maybe the repository should be renamed to better reflect its purpose?
