### ISSUE TITLE
Update the RoadMap, WishList and Done sections.

### ISSUE THREAD

**Issue by swarnimarun** [godotengine/roadmap#24]
Roadmap is an important part of any kind of software development and I think just to keep things in view of the developers and the users too.
**We could probably make it into a website too? Using GitHub Pages and link it to the godotengine.org website?**

I understand that everyone is busy so I can submit a PR too. And just to confirm.
Here's a list of things that I *think* have been completed, if there is more or something that is not there let me know.

- Animated Textures
- Bezier curve support
- Cinematic Stuff -- I think this is complete we the new Animation Player changes. Atleast partly.
- IK Support for skeletons
- Optional Typing
- Transition Graph 

I think all this should be moved to Done and probably more things that can be considered as significant feature updates. And I also think that done.md should have links to all the articles that represent the completed features and talk about them.
Just to clarify I will put everything we have as feature articles on GodotWebsite in the done section and probably some other major features too.

Now things to add to the RoadMap that I think are missing:

- Undocking of editor panels to separate windows
- Vulkan port

I don't know about the WishList, I can just add things there that I found in the Patreon polls as proposals? Or use some popular issues from github?

**Comment by fire** [comment]
As part of https://github.com/godotengine/godot-roadmap/pull/43 cleaning, we're not using this repository for roadmaps anymore.
