### ISSUE TITLE
Make materials and visualscript binary files be text based for 4.0

### ISSUE THREAD

**Issue by fire** [godotengine/roadmap#30]
> <iFire\>reduz: how difficult is it to make materials and visualscript binary files be text based?
> <reduz\>iFire: it requires severe hacking to resource format text, which I want to do eventually but not now
> <iFire\>reduz: I don't understand
> <reduz\>iFire: resource_format_text.h/cpp, needs hacking to make the scene part modular, and also support other formats this way like visual scripts and shaders
> <iFire\>reduz: are you able to describe the work in a proposal and someone will do the work because they care about it
> <reduz\>iFire: nope, this is probably too complex for someone not familiar with this code
> <reduz\>iFire: and a very critical part of the code, so it can only be touched by an actual maintainer
> <reduz\>bugs here can cause projects to corrupt silently, so this must be done by someone experienced
> <iFire\>reduz: from what you are saying it sounds like a beyond 4.0 release thing then.
> <iFire\>so probably more than 2 years from now?
> <reduz\>i have noted it for 4.0

**Comment by akien-mga** [comment]
Please file a proposal on https://github.com/godotengine/godot-proposals, which is the new tracker for feature requests.
