### ISSUE TITLE
Clear Console between Runs

### ISSUE THREAD

**Issue by ChipChance** [godotengine/roadmap#31]
Please either offer a command (like console.clear()) or a checkbox parameter to clear the console whenever a scene is run. Lately, I've been doing a 

for x in range(50): print("")

which gets the job done, but is lame! (lol.)

Thanks -

- Mike

**Comment by clayjohn** [comment]
This is not the correct repo to make this issue. If you are suggesting an enhancement to the engine or reporting a bug you should use the main repository found at https://github.com/godotengine/godot.

This repository is for discussing things related to the roadmap strictly.

**Comment by akien-mga** [comment]
Indeed, please open such suggestions on the main repository.

And the Output panel is already clearer on each run with the "run/output/always_clear_output_on_play" option which is ON by default, so I'm not sure what this proposals is asking for.
