### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by xtcPanda** [godotengine/roadmap#37]
I found that the CONTRIBUTING.md is not existing in the godot repo can I add it?

not every repo has one of these but it explains for someone like me trying to help contributing with this open source how to do it, if you want a new feature, a bug fix, support, if you want us to start contributing by filing an issue or you ignore them so we should do a pull request first..etc. These will be the things you do.

**Comment by akien-mga** [comment]
There's a CONTRIBUTING.md in the main Godot repo: https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md

This repository is for core contributors to document the roadmap, so it doesn't take contributions per se and doesn't need CONTRIBUTING.md IMO.

**Comment by xtcPanda** [comment]
ok sorry still trying <3 thank you though you're AWESOME !
