### ISSUE TITLE
Fix GSoC URL/Naming

### ISSUE THREAD

**Issue by personalizedrefrigerator** [godotengine/roadmap#38]
The URL posted on the Google Summer of Code overview page, `https://github.com/godotengine/godot-roadmap/blob/master/GSOC/GSOC-2020.md`, brings users to a 404 Error page. Please change this on the overview page to `https://github.com/godotengine/godot-roadmap/blob/master/GSoC/GSoC-2020.md` to make this page accessible.

**Comment by akien-mga** [comment]
Seems fixed already: https://summerofcode.withgoogle.com/organizations/6748100850352128/

**Comment by fire** [comment]
The url https://github.com/godotengine/godot-roadmap/blob/master/GSoC/GSoC-2020.md 

is different from

https://github.com/godotengine/godot-roadmap/blob/master/GSOC/GSOC-2020.md

Note lowercase o.

See https://summerofcode.withgoogle.com/organizations/6748100850352128/

**Comment by fire** [comment]
The broken link is at "Some ideas are outlined in our ideas list, but many other topics can be possible. The option is to find something that you're interested in and think would be a big improvement for the engine, and then discuss it with core developers on IRC to get initial feedback. We are here to help you shape the best proposal possible, so do not hesitate to ask us."

The ideas list link.

**Comment by akien-mga** [comment]
Thanks, I had missed that inline link and reviewed the most obvious one, which was correct:
![Screenshot_20200309_114055](https://user-images.githubusercontent.com/4701338/76205623-e29ed600-61fa-11ea-83cc-6d3fe23b81c3.png)

Fixed the other one now.

**Comment by anissen** [comment]
Some of the text is outdated, e.g.

> With its major 3.0 release in January 2018 and upcoming 3.1 release, (...)

**Comment by akien-mga** [comment]
> Some of the text is outdated, e.g.
> 
> > With its major 3.0 release in January 2018 and upcoming 3.1 release, (...)

Fixed.

**Comment by personalizedrefrigerator** [comment]
Thank you!
