### ISSUE TITLE
Variance shadow mapping

### ISSUE THREAD

**Issue by ghost** [godotengine/roadmap#4]
Variance shadow mapping was planned in [renderer TODO](https://docs.google.com/spreadsheets/d/1NRhaLNpW7yEH9pkZ48rQD7aLG6Z3WO2sdcBLqWkEqN8/edit#gid=0)

**Comment by reduz** [comment]
May eventually implement exponential shadow mapping, but not variance. It's too expensive and not enough benefit.

**Comment by Calinou** [comment]
If anyone stumbles upon this page via a Web search, note that Godot 4.0 has a much-improved shadow mapping implementation with the help of shadow pancaking. You can read more about it in [Vulkan progress report #7](https://godotengine.org/article/vulkan-progress-report-7).
