### ISSUE TITLE
DetourCrowd support

### ISSUE THREAD

**Issue by slapin** [godotengine/roadmap#5]
When considering Recast support, please pull DetourCrowd support too (that would be easier to do it this way than later). This gives nice crowds of individually and group-controllable agents which do not consume much CPU (for behaviors). Allows some complex behaviors in script.

**Comment by akien-mga** [comment]
Detour is used by godotengine/godot#34776. I'm not sure about the "Crowd" component, but if it's not included yet and should be, please file a proposal on https://github.com/godotengine/godot-proposals, which is the new tracker for feature requests.

**Comment by slapin** [comment]
Well, have you seen through the patch? It doesn't seem to use Detour at all.
Anyway feel free to close all my proposals, thy all seems to be irrelevant
now anyway.

**Comment by akien-mga** [comment]
Right I confused Detour and RVO2. If there's a need for DetourCrowd on top of the current feature, you can open a proposal on godot-proposals.
