### ISSUE TITLE
Behavior tree support

### ISSUE THREAD

**Issue by slapin** [godotengine/roadmap#6]
Implementing animation tree please give some time to implement Behavior tree which makes AI design much more easier and standard. Also decouples many systems making code clean. BTs are something which is easy to implement but gives a lot of power.

**Comment by guilhermefelipecgs** [comment]
@reduz Does the "Transition Graph" item in the roadmap mean "AnimationTreePlayer"?

**Comment by akien-mga** [comment]
Is this implemented as expected in AnimationTree? If not, please file a proposal on https://github.com/godotengine/godot-proposals, which is the new tracker for feature requests.
